### ISSUE TITLE
Freeze when getting the file creation date

### ISSUE THREAD

**Issue by lalejand** [ianare/metamorphose2#18]
Metamorphose is a great tool !!!!!
But I block on one bug that makes me unable to use it.
I want the filenames to be the creation date of the file.
When I configure the date so that it catches the file creation date, Metamorphose freezes.
Here is what I get in the terminal:
Traceback (most recent call last):
  File "/usr/share/metamorphose2/operations/dateTime.py", line 240, in get_from_item_checkbox
    self._test_time(event)
  File "/usr/share/metamorphose2/operations/dateTime.py", line 338, in _test_time
    main.show_preview(event)
  File "/usr/share/metamorphose2/MainWindow/__init__.py", line 620, in show_preview
    self.on_preview_button(False)
  File "/usr/share/metamorphose2/MainWindow/__init__.py", line 922, in on_preview_button
    self.renamer.preview(event)
  File "/usr/share/metamorphose2/renamer/__init__.py", line 72, in preview
    self.__preview.generate_names(event)
  File "/usr/share/metamorphose2/renamer/preview.py", line 225, in generate_names
    self.run(operations)
  File "/usr/share/metamorphose2/renamer/preview.py", line 304, in run
    newExt, itemToRename)
  File "/usr/share/metamorphose2/operations/replace.py", line 91, in rename_item
    newName = operations.parse_input(text, original, self)
  File "/usr/share/metamorphose2/operations/opButtons.py", line 185, in parse_input
    return self.parser.parse_input(text, file, operation)
  File "/usr/share/metamorphose2/operations/opParser.py", line 439, in parse_input
    value = self.__date_time(0, file, operation)
  File "/usr/share/metamorphose2/operations/opParser.py", line 296, in __date_time
    return utils.udate(main, dateTime[op + 1], itemDateTime)
  File "/usr/share/metamorphose2/utils.py", line 208, in udate
    udate = time.strftime(format.encode(main.encoding), itemDateTime)
LookupError: unknown encoding: None

**Comment by bastafidli** [comment]
This seems to be duplicate of #16
