### ISSUE TITLE
Ubuntu Mate 18.04

### ISSUE THREAD

**Issue by valentesolucoes** [ianare/metamorphose2#24]
$ metamorphose2
Traceback (most recent call last):
  File "/usr/share/metamorphose2/metamorphose2.py", line 188, in <module>
    main(wx_version, cli_options)
  File "/usr/share/metamorphose2/metamorphose2.py", line 173, in main
    import MainWindow
  File "/usr/share/metamorphose2/MainWindow/__init__.py", line 38, in <module>
    import sorting
  File "/usr/share/metamorphose2/sorting/__init__.py", line 25, in <module>
    from exif import EXIF
ImportError: No module named exif

**Comment by diogogomeswww** [comment]
I have the same problem in Ubuntu 17.10

**Comment by diogogomeswww** [comment]
I've finally manage to install metamorphose2 on my Ubuntu 18.04.

1. Clone the repo to your computer: 
`git clone git@github.com:diogogomeswww/metamorphose2.git`
`git submodule update --init`

2. On the root of the repo:
`make install`

3. If you don't have the dependencies install them:
`sudo apt-get install python-wxgtk3.0`
`sudo pip install Pillow`

4. Now you can run it by:
`metamorphose2`

Hope this helps!

**Comment by savoury1** [comment]
See #26 for a patched PPA build
