### ISSUE TITLE
ImportError:  cannot import name EXIF

### ISSUE THREAD

**Issue by javierpra** [ianare/metamorphose2#3]
On Freebsd when running `metamorphose2.py`

Traceback (most recent call last):
File "/usr/share/metamorphose2/metamorphose2.py", line 53, in <module>
  import MainWindow
File "/usr/share/metamorphose2/MainWindow/__init__.py", line 39, in <module>
  import sorting
File "/usr/share/metamorphose2/sorting/__init__.py", line 25, in <module>
  from exif import EXIF
ImportError: cannot import name EXIF

$ `pkg info|grep exif`
py27-exif-0.9_1                        Python library to extract EXIF metadata from JPEG and TIFF image files.

$ `ls src/exif/`
$

Looks like exif did not get pulled with git.  Will try again when internet is available. But a different exif module is installed with pkg.  Labelled as bug for now pending further testing.

**Comment by javierpra** [comment]
Looks to be an issue with .gitmodules.  Will run `git submodule` later in the day.

**Comment by javierpra** [comment]
Fixed by changing .gitmodules URL and path.
